### ISSUE TITLE
Is there any way to get the schema that results from applying $merge or $patch definitions?

### ISSUE THREAD

**Issue by azaslavsky** [epoberezkin/ajv-merge-patch#13]
For example, if I have the following two schemas:

```javascript
{
  "$id": "baseSchema",
  "type": "object",
  "properties": {
    "foo": {
      "type": "number"
    }
  }
}

{
  "$id": "schemaExtended",
  "$merge": {
    "source": { "$ref": "schemaExtended.json#" },
    "with": {
      "properties": {
        "foo": {
          "minimum": 0
        },
        "bar": {
          "type": "string"
        }
      }
    }
  }
}
```
Is there anyway to output the result of the merge operation?  Something like `ajv.getMergedSchema(schemaExtended);`, which would produce:

```javascript
{
  "$id": "schemaExtended",
  "type": "object",
  "properties": {
    "foo": {
      "type": "number",
      "minimum": 0
    }
    "bar": {
      "type": "string"
    }
  }
}
```

The reason I ask is that most other json-schema implementations do not support merge-patch, so it would be nice if there was some method by which JSON schemas that use these keywords could be converted to regular JSON schemas.

**Comment by epoberezkin** [comment]
This package implements $merge and $patch as custom keywords, it only uses resolved schemas in place, without generating full resolved schema.

It's relatively simple to generate the schema you want, using the same packages that are used here and json-schema-traverse.

It's worth publishing as a separate package I think - it could be used in ajv-cli package to add an additional command.
