### ISSUE TITLE
Merge schemas with required properties

### ISSUE THREAD

**Issue by tomasgvivo** [epoberezkin/ajv-merge-patch#31]
Given `schema1`
```
{
  type: 'object',
  properties: {
     properties: {
        foo: { type: "string" }
      },
  },
  required: ["foo"]
}
```

And given `schema2`
```
{
  $merge: {
    source: schema1,
    with: {
      type: 'object',
      properties: {
        bar: { type: "string" }
      },
      required: ["baz"]
    }
  }
}
```

I expect `foo` and `bar` to be required in `schema2`.
Instead, only `bar` is required.

Is this a bug or a feature?

**Comment by epoberezkin** [comment]
$merge does merging as defined in the related RFC (see the docs) - array values are supposed to be overwritten. $patch allows adding to arrays but with more complex syntax.
