### ISSUE TITLE
Using $merge with Fastify and shared schemas

### ISSUE THREAD

**Issue by PatrickHeneise** [epoberezkin/ajv-merge-patch#32]
I'm trying to put this together with fastify. I added ajv-merge-path as described in the docs into the validation (https://github.com/fastify/fastify/blob/master/lib/validation.js#L157)

example case:

schemas/defs.json

```json
{
  "$id": "/defs.json",
  "type": "object",
  "definitions": {
    "test": {
      "type": "object",
      "properties": {
        "name": { "type": "string" }
      }
    }
  }
}
```

schemas/foo.json

```json
{
  "$id": "/foo.json",
  "type": "object",
  "definitions": {
    "bar": {
      "type": "object",
      "$merge": {
        "source": {
          "$ref": "/defs.json#/definitions/test"
        },
        "with": {
          "properties": {
            "id": { "type": "string" }
          }
        }
      }
    }
  }
}
```

```js
fastify.get('/defs.json', (request, reply) => {
  reply.send(require('./schemas/defs'))
})
fastify.get('/foo.json', (request, reply) => {
  reply.send(require('./schemas/foo'))
})
fastify.post(
  '/',
  {
    schema: {
      body: { $ref: '/foo.json#/definitions/bar' }
    }
  },
  function(request, reply) {
    reply.send(fastify.getSchemas())
  }
)
```

- I'm not sure why I need to add the requests for the json files, but Swagger seems to need them
- The body in Swagger is empty. If I add `properties` directly to `foo`, everything works as expected, so the $merge doesn't work.

Any ideas how I can make this work?

**Comment by epoberezkin** [comment]
I think it should be submitted to fastify rather than here - most likely it simply doesn't support $merge. Also, fastify seems to use its own instance of ajv that doesn't have $merge added to it. Either fastify needs to add $merge to the instance or you need to pass your own instance (and it still doesn't mean $merge would work for anything but simple validation).

**Comment by PatrickHeneise** [comment]
Thanks, I'll check there.
